### ISSUE TITLE
License for this code?

### ISSUE THREAD

**Issue by GullyBurns** [Yoyodyne-Data-Science/ipynb-py-convert-databricks#1]
Hi there,

I was hoping to be able to reuse this code in my work. Are you releasing this work under an open source license? If so, could you specify what license would be most appropriate? MIT, Apache, CC0 etc?

Thanks!

Gully

**Comment by Yoyodyne-Data-Science** [comment]
Hi thanks, I have now added a licence to this repo,

Best of luck!
